basePath: /
definitions:
  api_model.CreateUser:
    properties:
      avatar:
        type: string
      email:
        type: string
      introduction:
        type: string
      nickname:
        type: string
      password:
        type: string
      passwordconfirm:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  api_model.Login:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  api_model.PostRole:
    properties:
      name:
        type: string
      policys:
        items:
          type: string
        type: array
      role_key:
        type: string
    type: object
  api_model.SetUserRole:
    properties:
      role_keys:
        items:
          type: string
        type: array
      usernames:
        items:
          type: string
        type: array
    type: object
  api_model.UpdatePolicy:
    properties:
      full_path:
        type: string
      label:
        type: string
      name:
        type: string
    type: object
  api_model.UpdateUser:
    properties:
      avatar:
        type: string
      email:
        type: string
      introduction:
        type: string
      nickname:
        type: string
      password:
        type: string
      passwordconfirm:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: hello@hello.io
    name: hello
    url: http://www.hello.io
  description: This is a hello server .
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://hello.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /options/role-option:
    get:
      description: RoleOption
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: RoleOption
      tags:
      - options
  /rbac/login:
    post:
      description: 登陆
      parameters:
      - description: Login
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/api_model.Login'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 登陆
      tags:
      - auth
  /rbac/logout:
    get:
      description: 登出
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 登出 （jwt 后端暂时无法登出）
      tags:
      - auth
  /rbac/policy:
    delete:
      description: delete policy
      parameters:
      - description: policy
        in: query
        name: policy
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete policy
      tags:
      - policy
    get:
      description: policy list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      - description: search
        in: query
        name: search
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: policy list
      tags:
      - policy
    put:
      description: UpdatePolicy
      parameters:
      - description: UpdatePolicy
        in: body
        name: UpdatePolicy
        required: true
        schema:
          $ref: '#/definitions/api_model.UpdatePolicy'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: UpdatePolicy
      tags:
      - policy
  /rbac/refresh_token:
    get:
      description: 刷新token
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 刷新token
      tags:
      - auth
  /rbac/role:
    delete:
      description: delete role
      parameters:
      - description: role_key
        in: query
        name: role_key
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete role
      tags:
      - role
    get:
      description: role list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: role list
      tags:
      - role
    post:
      description: create role
      parameters:
      - description: PostRole
        in: body
        name: PostRole
        required: true
        schema:
          $ref: '#/definitions/api_model.PostRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: create role
      tags:
      - role
    put:
      description: Update role
      parameters:
      - description: PostRole
        in: body
        name: PostRole
        required: true
        schema:
          $ref: '#/definitions/api_model.PostRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Update role
      tags:
      - role
  /rbac/role/userrole:
    put:
      description: SetUserRole
      parameters:
      - description: SetUserRole
        in: body
        name: SetUserRole
        required: true
        schema:
          $ref: '#/definitions/api_model.SetUserRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: SetUserRole
      tags:
      - role
  /rbac/user:
    delete:
      description: delete user
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete user
      tags:
      - user
    get:
      description: user list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      - description: search
        in: query
        name: search
        type: string
      - description: role_key
        in: query
        name: role_key
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: user list
      tags:
      - user
    post:
      description: CreateUser
      parameters:
      - description: CreateUser
        in: body
        name: CreateUser
        required: true
        schema:
          $ref: '#/definitions/api_model.CreateUser'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: CreateUser
      tags:
      - user
    put:
      description: UpdateUser
      parameters:
      - description: UpdateUser
        in: body
        name: UpdateUser
        required: true
        schema:
          $ref: '#/definitions/api_model.UpdateUser'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: UpdateUser
      tags:
      - user
  /rbac/user/info:
    get:
      description: user info
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: user info
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
