basePath: /
definitions:
  api_model.CreateUser:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      passwordconfirm:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  api_model.PostRole:
    properties:
      name:
        type: string
      role:
        type: string
    type: object
  api_model.SetRoleByUserName:
    properties:
      roles:
        items:
          type: string
        type: array
      username:
        type: string
    type: object
  api_model.SetRoleMenus:
    properties:
      menus:
        items:
          type: string
        type: array
      role:
        type: string
    type: object
  api_model.UpdateUser:
    properties:
      email:
        type: string
      nickname:
        type: string
      password:
        type: string
      passwordconfirm:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  model.MenuOut:
    properties:
      alwaysshow:
        type: integer
      auto_create:
        type: integer
      children:
        items:
          $ref: '#/definitions/model.MenuOut'
        type: array
      component:
        type: string
      hidden:
        type: integer
      icon:
        type: string
      id:
        type: integer
      menu_name:
        type: string
      menu_path:
        type: string
      name:
        type: string
      nocache:
        type: integer
      parent_name:
        type: string
      redirect:
        type: string
      sort:
        type: integer
      title:
        type: string
    type: object
info:
  contact:
    email: hello@hello.io
    name: hello
    url: http://www.hello.io
  description: This is a hello server .
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://hello.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /loginkey:
    get:
      description: 获取登录的加密key
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取登录的加密key
      tags:
      - auth
  /logout:
    post:
      description: 登出
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 登出
      tags:
      - auth
  /menu:
    delete:
      description: delete menu
      parameters:
      - description: name
        in: query
        name: name
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete menu
      tags:
      - menu
    get:
      description: menu list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: menu list
      tags:
      - menu
    post:
      description: create menu
      parameters:
      - description: MenuOut
        in: body
        name: SignInInfo
        required: true
        schema:
          $ref: '#/definitions/model.MenuOut'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: create menu
      tags:
      - user
    put:
      description: update menu
      parameters:
      - description: MenuOut
        in: body
        name: SignInInfo
        required: true
        schema:
          $ref: '#/definitions/model.MenuOut'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: update menu
      tags:
      - user
  /policy:
    get:
      description: policy list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: policy list
      tags:
      - policy
    post:
      description: create role
      parameters:
      - description: PostRole
        in: body
        name: PostRole
        required: true
        schema:
          $ref: '#/definitions/api_model.PostRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: create role
      tags:
      - role
    put:
      description: SetPolicyByRole
      parameters:
      - description: PostRole
        in: body
        name: PostRole
        required: true
        schema:
          $ref: '#/definitions/api_model.PostRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: SetPolicyByRole
      tags:
      - policy
  /policy/byrole:
    get:
      description: GetPolicyByRole
      parameters:
      - description: role
        in: query
        name: role
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: GetPolicyByRole
      tags:
      - policy
  /role:
    delete:
      description: delete role
      parameters:
      - description: role
        in: query
        name: role
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete role
      tags:
      - role
    get:
      description: role list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      - description: username
        in: query
        name: username
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: role list
      tags:
      - role
    put:
      description: Update role
      parameters:
      - description: PostRole
        in: body
        name: PostRole
        required: true
        schema:
          $ref: '#/definitions/api_model.PostRole'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Update role
      tags:
      - role
  /role/byuser:
    put:
      description: SetRoleByUserName
      parameters:
      - description: SetRoleByUserName
        in: body
        name: SetRoleByUserName
        required: true
        schema:
          $ref: '#/definitions/api_model.SetRoleByUserName'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: SetRoleByUserName
      tags:
      - role
  /role/menu:
    put:
      description: SetRoleMenus
      parameters:
      - description: SetRoleMenus
        in: body
        name: SetRoleMenus
        required: true
        schema:
          $ref: '#/definitions/api_model.SetRoleMenus'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: SetRoleMenus
      tags:
      - role
  /user:
    delete:
      description: delete user
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: delete user
      tags:
      - user
    get:
      description: user list
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: limit
        in: query
        name: limit
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: user list
      tags:
      - user
    post:
      description: CreateUser
      parameters:
      - description: CreateUser
        in: body
        name: CreateUser
        required: true
        schema:
          $ref: '#/definitions/api_model.CreateUser'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: CreateUser
      tags:
      - user
    put:
      description: UpdateUser
      parameters:
      - description: UpdateUser
        in: body
        name: UpdateUser
        required: true
        schema:
          $ref: '#/definitions/api_model.UpdateUser'
          type: object
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: UpdateUser
      tags:
      - user
  /user/info:
    get:
      description: user info
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: user info
      tags:
      - user
  /user/menu:
    get:
      description: user menu
      parameters:
      - description: RoleConfig
        in: query
        name: RoleConfig
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: user menu
      tags:
      - user
swagger: "2.0"
