# Generated by Django 2.1.4 on 2019-08-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=255)),
                ('v0', models.CharField(max_length=255)),
                ('v1', models.CharField(max_length=255)),
                ('v2', models.CharField(max_length=255)),
                ('v3', models.CharField(max_length=255)),
                ('v4', models.CharField(max_length=255)),
                ('v5', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'casbin_rule',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_path', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('redirect', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hidden', models.IntegerField(blank=True, null=True)),
                ('alwaysshow', models.IntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('auto_create', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='MenuMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('nocache', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'menu_meta',
            },
        ),
        migrations.CreateModel(
            name='PolicyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_path', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('descrption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'policy_name',
            },
        ),
        migrations.CreateModel(
            name='RoleMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=255)),
                ('menu_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'role_menu',
            },
        ),
        migrations.CreateModel(
            name='RoleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('descrption', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'role_name',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('nick_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.IntegerField()),
                ('age', models.IntegerField()),
                ('add_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('add_user_id', models.IntegerField()),
                ('introduction', models.CharField(blank=True, db_column='Introduction', max_length=255, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
