# Generated by Django 2.1.4 on 2019-08-08 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoleConfig',
            new_name='RoleName',
        ),
        migrations.AlterModelTable(
            name='casbinrule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menumeta',
            table=None,
        ),
        migrations.AlterModelTable(
            name='policyname',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rolemenu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rolename',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
