# Generated by Django 2.1.4 on 2019-08-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role_keys',
        ),
        migrations.AddField(
            model_name='policyconfig',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
