# Generated by Django 2.1.4 on 2019-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0002_auto_20190822_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='auto_create',
        ),
        migrations.RemoveField(
            model_name='menumeta',
            name='menu_name',
        ),
        migrations.RemoveField(
            model_name='menumeta',
            name='nocache',
        ),
        migrations.AddField(
            model_name='menumeta',
            name='menu_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
