# Generated by Django 2.1.4 on 2019-09-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0002_auto_20190831_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
