# Generated by Django 2.1.4 on 2019-08-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0002_auto_20190822_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parent_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='parent_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
