# Generated by Django 2.1.4 on 2019-08-08 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0002_auto_20190808_0343'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolicyName',
            new_name='PolicyConfig',
        ),
        migrations.RenameModel(
            old_name='RoleName',
            new_name='RoleConfig',
        ),
    ]
