# Generated by Django 2.1.4 on 2019-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0003_auto_20190822_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.CharField(db_index=True, max_length=255)),
                ('user_name', models.CharField(max_length=255)),
            ],
        ),
    ]
