# Generated by Django 2.1.8 on 2019-08-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gadmin', '0004_auto_20190823_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
